import localFont from "next/font/local";

import "./globals.css";

import dynamic from "next/dynamic";
import { NProgressBar } from "@/components/NProgress";

const Navbar = dynamic(() => import("@/components/layout/Navbar"), {
    ssr: false,
});

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Next App Jwt Demo",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="bg-slate-100 subpixel-antialiased">
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-slate-100 font-sans text-black antialiased`}
            >
                <NProgressBar />
                <main className="w-full">
                    <Navbar />
                    <div className="px-10">{children}</div>
                </main>
            </body>
        </html>
    );
}
